kind: Pod 
apiVersion: v1 
metadata: 
  name: nodelabels
  labels: 
    env: dev 
spec: 
  containers: 
  - name: c00
    image: ubuntu 
     command: ["/bin/bash","-c","while true; do echo hiii; sleep 5; done"]
  nodeSelector: 
    hardware: t2-medium
