kind: ReplicationController 
apiVersion: v1
metadata: 
  name: myreplica
spec: 
  replicas: 2
  selector: 
    myname: vikrant wagh
  template: 
    metadata: 
      name: testpod
      labels: 
        myname: vikrant
    spec:
      containers:
      - name: c00
        imange: unbuntu
        command: ["/bin/bash","-c","while true; do echo hellow vikrant; sleep 5; done"]
